buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.2"
        classpath "com.chaquo.python:gradle:17.0.0"
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
